import Head from "next/head";

import styles from "./index.module.css";
import { SignInButton, useUser } from "@clerk/nextjs";
import { type RouterOutputs, api } from "~/utils/api";
import { type NextPage } from "next";
import Image from "next/image";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingPage } from "~/components/loading";
import { useState } from "react";
dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  const [input, setInput] = useState("");

  const ctx = api.useUtils();

  const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess: () => {
      setInput("");
      void ctx.posts.getAll.invalidate();
    },
  });

  if (!user) return null;

  return (
    <div className={styles.profileImageContainer}>
      <Image
        width={200}
        height={200}
        className={styles.profileImage}
        src={user.imageUrl}
        alt="Profile image"
      />
      <input
        className={styles.emojiInput}
        placeholder="Type some emojis!"
        type="text"
        value={input}
        onChange={(e) => setInput(e.target.value)}
        disabled={isPosting}
      />
      <button onClick={() => mutate({ content: input })}>Post</button>
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;

  return (
    <div className={styles.post}>
      <Image
        width={200}
        height={200}
        className={styles.profileImage}
        src={author.profilePicture}
        alt={`@${author.name}'s profile picture`}
      />
      <div className={styles.postContent}>
        <div className={styles.postAuthor}>
          <span>{`@${author.name}`}</span>
          <span>·</span>
          <span className={styles.postTime}>
            {dayjs(post.createdAt).fromNow()}
          </span>
        </div>
        <span className={styles.postText}>{post.content}</span>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (postsLoading) return <LoadingPage />;

  if (!data) return <div>Something went wrong.</div>;

  return (
    <div className={styles.postContainer}>
      {data.map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  // Start fetching ASAP
  api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.mainContent}>
          <div className={styles.topNav}>
            {!isSignedIn && <SignInButton />}
            {!!isSignedIn && (
              <>
                <CreatePostWizard />
              </>
            )}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
