import Head from "next/head";

import styles from "../index.module.css";
import { type NextPage } from "next";

const PostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>Post view</div>
      </main>
    </>
  );
};

export default PostPage;
